### ISSUE TITLE
Ouput definition file overwriting the input file

### ISSUE THREAD

**Issue by leouieda** [achennu/microbenthos#5]
@achennu in the [Usage docs](https://microbenthos.readthedocs.io/en/develop/usage.html#running-simulations) there is a note saying:

> The default name for the output definition file is definition.yml. So if your input file is called definition.yml, then it will get overwritten on running the command.

Wouldn't it be better to check if the input and output names are the same and raise an exception instead? Or ask the user if that's OK? I see that there are confirmation messages for overwriting the simulation HDF5 output.

Related to openjournals/joss-reviews#674

**Comment by achennu** [comment]
@leouieda that's well spotted. However, it is deliberately so. The idea is that the definition file supplied by the user goes through a validation. At this stage, the definition dictionary becomes fully explicit, i.e. the implicit and default parameters get filled out, and so the written ``definition.yml`` file is complete. 
So what could happen is:
* The user's input file does not get validated, in which case nothing is written to disk. Problems in the definition file are listed on the console, so the user can correct them.
* The user can check if the input they provide can be validated by using the ``microbenthos export model`` command.
* If the definition file gets validated, then the validated dictionary is written to ``definition.yml``. In this step, no information is lost (only enhanced). 

The ``definition.yml`` file is the starting point for the simulations. On running one, a ``runner.yml`` file captures the library versions used in the runtime. Then when data is produced, it gets stored into the ``simulation_data.h5`` store. With this setup, having the definition file and the data file is enough to resume a simulation. Technically, all the information for the simulation is already stored in the metadata of the hdf file, but there are additional steps I have implemented to ensure that a model cannot be 'wrongly' resumed leading to spurious data. I had considered to include docs about this, but I'd need some more testing to ensure it as a guarantee.

As such, the checks for overwriting are not performed for the defnition or runner files, but mainly for the data file only -- which can either be resume, or overwrite.

**Comment by leouieda** [comment]
OK, so `definition.yml` is a completed version of the input file. That makes sense. It's a smart way to preserve saved simulations from changes in default parameters in future releases.

Have you considered using `tempfile.NamedTemporaryFile` to generate a unique ID for each simulation? You can append this ID to the end of every file name so you'd have `simulation_data_ID.h5` and `definition_ID.yml`. They can still know of each other through the ID and  repeated runs won't cause files to be overwritten. I use this in [GMT/Python to generate unique figure names](https://github.com/GenericMappingTools/gmt-python/blob/26c4849706f233a01854e727b030dfedb6c25efd/gmt/helpers/tempfile.py#L10).

**Comment by achennu** [comment]
I did start with a unique id based tagging of the simulation definition and data files. However, the point of modelling is to compare the changes in the parameters on some metric. Running a family of simulations, I soon realized that it becomes difficult to keep track of which run has which parameters based on just a random unique id. I instead developed a rig to run each simulation in parallel and the natural output of a run is a separate directory. Easier to parse, navigate and prune. In a future version, I may include this parallel running setup into the repo.

Will close this issue for now. Thanks for the input!

**Comment by leouieda** [comment]
Yep, that makes sense if you're running a whole bunch of simulations. A possible compromise would be use the random id by default but you can overwrite when you know where you want to save your files.  Anyway, these are just some ideas.

Great work!
